repos:
- repo: https://github.com/awslabs/git-secrets
  rev: 5357e18bc27b42a827b6780564ea873a72ca1f01 # Must be post the 1.3.0 release
  hooks:
  - id: git-secrets
    entry: git-secrets --scan
    files: .
    args: [--untracked]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    # Git style
    - id: check-added-large-files
    - id: check-merge-conflict
    - id: check-vcs-permalinks
    - id: forbid-new-submodules
    - id: no-commit-to-branch

    # Common errors
    - id: end-of-file-fixer
      exclude: (\.asc)$
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]
      exclude: CHANGELOG.md
    - id: check-yaml
      args: [--allow-multiple-documents]
    - id: check-merge-conflict
    - id: check-executables-have-shebangs

    # Cross platform
    - id: check-case-conflict
    - id: mixed-line-ending
      args: [--fix=lf]

    # Security
    - id: detect-aws-credentials
      args: ['--allow-missing-credentials']
    - id: detect-private-key

# Check shell scripts example
- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 3.0.0
  hooks:
    - id: shfmt
      args: ['-l', '-i', '2', '-ci', '-sr', '-w']
    - id: shellcheck

- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.88.4
  hooks:
    - id: terraform_fmt
      files: (\.tf|\.tfvars)$
      exclude: \.terraform\/.*$

    - id: terraform_providers_lock
      files: (\.terraform\.lock\.hcl)$
      exclude: \.terraform\/.*$
      args:
         - --args=-platform=linux_amd64
         - --args=-platform=darwin_amd64
         - --args=-platform=darwin_arm64

    - id: terraform_tflint
      args:
      - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
      files: (\.tf|\.tfvars)$
      exclude: (\.terraform.*)$

    - id: terraform_docs
      args:
        - --args=--config=.terraform-docs.yml
